In [1]:
import numpy as np
from solution import *

In [2]:
data = np.loadtxt("train.csv", delimiter=',', dtype=np.int32)

In [3]:
data

array([[   5,   44,    6, ...,   38, -122,    0],
       [   2,   17,    4, ...,   39, -122,    0],
       [   4,    4,    4, ...,   38, -122,    0],
       ...,
       [   3,   30,    5, ...,   36, -119,    0],
       [   7,   38,    7, ...,   37, -122,    0],
       [   3,   48,    5, ...,   38, -123,    0]])

In [4]:
get_entropy(0, 1)

0.0

In [5]:
features = data[:, :-1]
labels = data[:, -1]

In [14]:
get_best_separation(features, labels)

(7, -119)

In [20]:
tree = build_tree(features, labels)

In [15]:
a = np.array([1, 2, 2, 2, 3, 1, 1])
np.unique(a)

array([1, 2, 3])

In [16]:
a = np.array([2, 5, 8, 12, 3])
b = np.array([1, 6, 9, 8, 5])
sep_val = 5

a_result = a[a >= sep_val]
b_result = b[a >= sep_val]

print("A eredmény:", a_result)
print("B eredmény:", b_result)

A eredmény: [ 5  8 12]
B eredmény: [6 9 8]


In [17]:
import numpy as np

c = np.array([0, 1, 1, 0, 1, 1, 0])

num_ones = np.sum(c)
num_zeros = len(c) - np.sum(c)
print("Az egyesek száma:", num_ones)
print("A nullák száma:", num_zeros)

Az egyesek száma: 4
A nullák száma: 3


In [18]:
array_ones = np.array([1, 1, 1, 1, 1])
array_zeros = np.array([0, 0, 0, 0, 0])
arr = np.array([])

check_ones = np.all(array_ones == 1)
check_zeros = np.all(array_zeros == 0)

print("Csak 1-esekből áll:", check_ones)
print("Csak 0-ásokból áll:", check_zeros)

print(f"csak 1: {np.all(arr == 1)}, csak 0: {np.all(arr == 0)}")

Csak 1-esekből áll: True
Csak 0-ásokból áll: True
csak 1: True, csak 0: True


In [19]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

column_index = 1  # Példa: az 1-es indexű oszlopot töröljük

new_matrix = np.delete(matrix, column_index, axis=1)
new_matrix = np.delete(new_matrix, column_index, axis=1)
print(new_matrix)


[[1]
 [4]
 [7]]


In [21]:
arr = np.array([1, 2, 3, 4])
np.delete(arr, 2)

array([1, 2, 4])